//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public int ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<bool> ForceUpdateAdmin { get; set; }
        public string AppVersionAdmin { get; set; }
        public Nullable<bool> ForceUpdateGame { get; set; }
        public string AppVersionGame { get; set; }
    }
}
