//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinLatLong
    {
        public int Id { get; set; }
        public string lat { get; set; }
        public string @long { get; set; }
        public string Distance { get; set; }
        public string Temp { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
