//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceDetail
    {
        public int DeviceDetailId { get; set; }
        public string DeviceID { get; set; }
        public string FCMID { get; set; }
        public string DeviceType { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
    }
}
