//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogelHitDetail
    {
        public int Id { get; set; }
        public string API { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> hit { get; set; }
    }
}
