//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID_Master
    {
        public int ID { get; set; }
        public string ReaderID { get; set; }
        public string TagID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
