//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GetLiquidNumber
    {
        public int LWId { get; set; }
        public string ReferanceId { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
